# Generated by Django 3.2.3 on 2021-07-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMoneda',
            fields=[
                ('idMoneda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id moneda')),
                ('nombreMoneda', models.CharField(max_length=50, verbose_name='Nombre moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('numero_identificaion', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero de Identificacion')),
                ('nombre_completo', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('email', models.CharField(max_length=20, verbose_name='Email')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Constraseña')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groundzero.tipomoneda')),
            ],
        ),
    ]
